server:
  port: 8100

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: book-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/bookservice?useTimezone=true&serverTimezone=UTC&currentSchema=bookservice
    username: postgres
    password: a
  flyway:
    url: jdbc:postgresql://localhost:5432/bookservice
    schemas: bookservice
    user: postgres
    password: a
  jackson:
    default-property-inclusion: NON_NULL
    serialization:
      fail-on-empty-beans: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect


