spring:
  application:
    name: greeting-service

greeting-service:
  greeting: "Olá"
  default-value: "Mundo Production Alterado agora com o Refresh"

management:
  endpoints:
    web:
      exposure:
        include:
          - '*'